---

- name: copy stream includes config file
  template:
    src: "{{ nginx_dir_prefix }}/stream-conf/{{ config.name }}"
    dest: "{{ nginx_dir_etc }}/stream.d/conf-available/"
    owner: root
    group: "{{ nginx_group }}"
    mode: 0640
  with_items: "{{ nginx_stream_conf }}"
  loop_control:
    loop_var: config
  notify:
    - restart nginx

- name: enable stream includes config file
  file:
    src: "{{ nginx_dir_etc }}/stream.d/conf-available/{{ config.name }}"
    dest: "{{ nginx_dir_etc }}/stream.d/conf-enabled/{{ config.name }}"
    owner: root
    group: "{{ nginx_group }}"
    state: link
  with_items: "{{ nginx_stream_conf }}"
  loop_control:
    loop_var: config
  when: config.enabled
  notify:
    - restart nginx

- name: disable stream includes config file
  file:
    path: "{{ nginx_dir_etc }}/stream.d/conf-enabled/{{ config.name }}"
    state: absent
  with_items: "{{ nginx_stream_conf }}"
  loop_control:
    loop_var: config
  when: not config.enabled
  notify:
    - restart nginx

- name: copy stream includes site file
  template:
    src: "{{ nginx_dir_prefix }}/stream-site/{{ config.name }}"
    dest: "{{ nginx_dir_etc }}/stream.d/site-available/"
    owner: root
    group: "{{ nginx_group }}"
    mode: 0640
  with_items: "{{ nginx_stream_sites }}"
  loop_control:
    loop_var: config
  notify:
    - restart nginx

- name: enable stream includes site file
  file:
    src: "{{ nginx_dir_etc }}/stream.d/site-available/{{ config.name }}"
    dest: "{{ nginx_dir_etc }}/stream.d/site-enabled/{{ config.name }}"
    owner: root
    group: "{{ nginx_group }}"
    state: link
  with_items: "{{ nginx_stream_sites }}"
  loop_control:
    loop_var: config
  when: config.enabled
  notify:
    - restart nginx

- name: disable stream includes site file
  file:
    path: "{{ nginx_dir_etc }}/stream.d/site-enabled/{{ config.name }}"
    state: absent
  with_items: "{{ nginx_stream_sites }}"
  loop_control:
    loop_var: config
  when: not config.enabled
  notify:
    - restart nginx
