---

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - always

- name: include package tasks
  include: packages-{{ ansible_os_family }}.yml
  tags:
    - nginx
    - nginx:package

- name: include setup tasks
  include: setup.yml
  tags:
    - nginx
    - nginx:setup

- name: include http config tasks
  include: config-http.yml
  when: nginx_server_http
  tags:
    - nginx
    - nginx:config

- name: include mail config tasks
  include: config-mail.yml
  when: nginx_server_mail
  tags:
    - nginx
    - nginx:config

- name: include stream config tasks
  include: config-stream.yml
  when: nginx_server_stream
  tags:
    - nginx
    - nginx:config

- name: include main config tasks
  include: config-main.yml
  tags:
    - nginx
    - nginx:config

- name: include service tasks
  include: service.yml
  tags:
    - nginx
    - nginx:service
