---
- name: create config directories
  file:
    path: "{{ nginx_dir_etc }}/{{ directory }}"
    owner: root
    group: "{{ nginx_group }}"
    mode: 0750
    state: directory
  with_items:
    - http.d/conf-available
    - http.d/conf-enabled
    - http.d/sites-available
    - http.d/sites-enabled
    - mail.d/conf-available
    - mail.d/conf-enabled
    - mail.d/sites-available
    - mail.d/sites-enabled
    - stream.d/conf-available
    - stream.d/conf-enabled
    - stream.d/sites-available
    - stream.d/sites-enabled
    - main.d/conf-available
    - main.d/conf-enabled
  loop_control:
    loop_var: directory
