---
- name: Converge
  hosts: all
  roles:
    - role: ansible_nginx
      nginx_test: True
      nginx_dir_prefix: "{{ playbook_dir }}/../default/files"
      nginx_main_conf:
        - {'name': 'events.conf', 'enabled': True}
